# optional parameter spring.throttling.lru-cache-capacity, default value is 10000
spring:
  throttling:
    lru-cache-capacity: 100

  application:
    name: example

logging:
  level:
    ROOT: ERROR
    com.weddini.throttling: DEBUG
